/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controles;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author juanalvarenga
 */
public class LoginPage extends javax.swing.JFrame {

    //credenciales
    // clave / valor
    HashMap<String, String> credenciales = new HashMap();
    HashMap<String, String> credenciales2 = new HashMap();
    HashMap<String, String> credenciales3 = new HashMap();

    HashMap[] usuarios = new HashMap[3];
    ArrayList<HashMap> listadoUsuarios = new ArrayList();

//     [ {usuario=juan,contrasenia=1234},{usuario=juan,contrasenia=1234},{usuario=juan,contrasenia=1234} ]
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();

        credenciales.put("usuario", "admin");
        credenciales.put("contrasenia", "1234");

        credenciales2.put("usuario", "caja");
        credenciales2.put("contrasenia", "1122");

        credenciales3.put("usuario", "reportes");
        credenciales3.put("contrasenia", "3344");

        usuarios[0] = credenciales;
        usuarios[1] = credenciales2;
        usuarios[2] = credenciales3;

        listadoUsuarios.add(credenciales);
        listadoUsuarios.add(credenciales2);
        listadoUsuarios.add(credenciales3);

    }

//    int[] numeros = {1,2,3,4,5,6}; // [ 1, 2, 3, 4, 5, 6 ]
//    
//    int[] numeros2 = new int[3];
    void login() {

        String user = txtUsuario.getText();
        String pwd = String.valueOf(txtContrasenia.getPassword());

        //        for( HashMap usuario : usuarios ){
//            
//            if (user.trim().equals(usuario.get("usuario"))
//                    && pwd.trim().equals(usuario.get("contrasenia"))) {
//
//                JOptionPane.showMessageDialog(this, "Bienvenido", "Pantalla principal", JOptionPane.INFORMATION_MESSAGE);
//                return;
//
//            }
//        }


        HashMap temp = new HashMap();
        temp.put("usuario", user);
        temp.put("contrasenia", pwd);

        boolean result = listadoUsuarios.contains(temp);
        
        if (result) {
            
            JOptionPane.showMessageDialog(this, "Bienvenido", "Pantalla principal", JOptionPane.INFORMATION_MESSAGE);
            
            //Instanciar la nueva ventana
            FormularioPage formulario = new FormularioPage();
            //Mostrarla
            formulario.setVisible(true);
            
            //ocultar la pantalla anterior
            this.dispose();
            
            
            return;
        }


        //NO puedo acceder al sistema
        JOptionPane.showMessageDialog(this, "Acceso no autorizado", "Error al iniciar sesión", JOptionPane.ERROR_MESSAGE);

        //HashMap
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        txtContrasenia = new javax.swing.JPasswordField();
        terminos = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inicio de sesión");
        setAlwaysOnTop(true);

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        txtUsuario.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N

        btnLogin.setText("Iniciar sesion");
        btnLogin.setEnabled(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtContrasenia.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N

        terminos.setText("Aceptar terminos de licencia");
        terminos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(terminos)
                    .addComponent(btnLogin)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario)
                            .addComponent(txtContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(terminos)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void terminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminosActionPerformed
        // TODO add your handling code here:

//        System.out.println(terminos.isSelected());
        btnLogin.setEnabled(terminos.isSelected());

//        if(terminos.isSelected()) {
//            btnLogin.setEnabled(true);
//        } else {
//            btnLogin.setEnabled(false);
//        }

    }//GEN-LAST:event_terminosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox terminos;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
